import { sequelize } from "./models/db.js";
console.log("Cleaning all enrollment data and resetting sections...");
await sequelize.query("DELETE FROM enrollment_subjects");
await sequelize.query("DELETE FROM enrollment_documents");
await sequelize.query("DELETE FROM enrollment_records");
await sequelize.query("UPDATE sections SET currentEnrollment = 0");
const [users] = await sequelize.query("SELECT id, name, email, role FROM users ORDER BY role");
console.log("Current users:");
users.forEach(u => console.log(`  [${u.role}] ${u.name} (${u.email})`));
console.log("Done! All enrollments cleared, sections reset to 0.");
process.exit(0);
